### PR TITLE
Proposals version 2. Iteration 2.

### PR DESCRIPTION
**Pull request by shamil-gadelshin**

### CODE REVIEW

**Comment by bedeho** [comment]
Why does this PR target `integrate-content-wg`? Should it not target `development` or some long-running feature branch for all the work we plan to do on the proposal system?

**Comment by shamil-gadelshin** [comment]
This PR targets `integrate-content-wg` because It is current latest dev version. It can be tested with the latest node and Apps. And integration tests had already allowed me to fix 2 bugs.

**Comment by bedeho** [comment]
In that case it makes more sense to just rebase it on top of this branch, and still target `development`.

Also, lets have this as a long-running feature branch, so all future work is PRs that fork off and target this branch. The name is a bit conflicting, so if you want to you can fix that.

**Comment by bedeho** [comment]
I guess we can close this.

**Pull request closed without merging**
